### PR TITLE
Expanded export functionality updates

### PR DESCRIPTION
**Pull request by schroef**
Please note, my index still has the old layout compared to your version. When merging, choose to adjust it again or keep it like this. Perhaps i should adjust the layout, im not 100% convinced about how the destination folder part looks. The input showing the path is very narrow 

### Added
- Allow custmo alert dialog to show different icons
- Extra warnings when something goes wrong running functions. Some lacked proper feedback to user

### Fixed
- Export EPS export wrong artboard range. all artboards were exported to all logo variation folders
- Not showing error when destination folder could not be opened or was not found
- Cancel clear destination folder would still delete/clear the folder

### Others
- Reorganised custom alert dialog, moved to hostscript for easier access
- Cleanup code & leftovers

### Fixed
- Issue when conversion to Grayscale due to new added PMS. colors were much lighter

### Added
- Document Color Profile mismatch from Color Settings warning and option to show Assign Window so profiles will match
- Custom Alert Dialog, closer to Script UI design

### Added
- PMS conversion method and updated Panel layout

### Added
- Export Settings Dialog implemention, settings can now be customized
- Auto margin updates works for logoinfo as well know

### Added
- Integrated into panel layout & design of dialog

### Added
- Add color ouputs checkboxes
- Design Export Settings Dialog

### Added
- Color Output checkboxes, users can now define what color variations are output

### Fixed
- Issue with generation new logos when initial created document was close. Issue with initialArtboardLength was kept in memory

### Fixed
- Logo type info would not adjust its location when margins being adjusted, now it gets repositioned based on the added margin (still need work when logo color types are taken out)

### Fixed
- clear destination folder did not clean EPS files

### Added
- Better check disabling PNG export for print logo types
- Margins change automatically on changing the input value

### Added
- EPS file export types
- Check to PNG export, disables option for print logo types

### Fixed
- RasterEffecy Settings, now check if document is either for print or digital and adjust the DPI settings

### CODE REVIEW

**Comment by mevCJ** [comment]
@schroef thanks for the contribution! I've updated the layout. The reason of putting the folder icon beside destination input is because it lets user to be able to find the button more easily as elements with the same function are grouped together. 

I've also updated the cmyktopms.jsx from jsxbin to jsx and fixed some bugs in that script.

**Comment by schroef** [comment]
Did it had bugs? Didn't noticed that. Where you able to decipher the jsxbin file easily?

One side note. With he new illustrator version lacking pms libraries. I'm not sure we are allowed to do this now. Though on hand, we just add a name a lab value. They don't own lab values. But perhaps i need toch this better 


Please don't use the converted jsx of cmyktopms. There was a reason i coded it

**Comment by mevCJ** [comment]
I used a script here https://github.com/AngeloD2022/jsxbin_decompiler

The script only changes the color of the first item in a groupItems object. I've added another condition for groupitems so that it changes everything in a group.

Just wondering, where did you get the script from?

**Comment by schroef** [comment]
I tested it many times and worked fine for me with group items.


I've made script myself using a combination of different scripts. I've used parts of code to make this functionality possible with just a single script. The original script used an extra ai file which had stored all pms colors, but i found that cumbersome. So i packed all colors and color values in a single script. It would also only do the swatches inside a file, it didn't do a selected item. I used a different script so that it would itterste over parts inside a selected group. That worked fine on my end.

I prefer we keep this on jwxbin mode

**Comment by schroef** [comment]
I see what you meant with the group issue. I always tend to group a logo. So basically nothing was changed in the cmyktopms, i see you reordered some lines. But please keep it in jsxbin format!

**Pull request merged**
